### ISSUE TITLE
NPE from ApacheClientSpanDecorator

### ISSUE THREAD

**Issue by safetytrick** [opentracing-contrib/java-apache-httpclient#12]
I'm seeing an NPE from this library when setting the hostname tag on a trace, I believe this only happens when the apache library is executing a retry?

    java.lang.NullPointerException
	at java.util.concurrent.ConcurrentHashMap.putVal(ConcurrentHashMap.java:1011)
	at java.util.concurrent.ConcurrentHashMap.put(ConcurrentHashMap.java:1006)
	at io.opentracing.contrib.api.tracer.APIExtensionsSpan.handleSetTag(APIExtensionsSpan.java:214)
	at io.opentracing.contrib.api.tracer.APIExtensionsSpan.setTag(APIExtensionsSpan.java:194)
	at io.opentracing.tag.StringTag.set(StringTag.java:25)
	at io.opentracing.contrib.apache.http.client.ApacheClientSpanDecorator$StandardTags.onRequest(ApacheClientSpanDecorator.java:64)
	at io.opentracing.contrib.apache.http.client.TracingClientExec.handleNetworkProcessing(TracingClientExec.java:138)
	at io.opentracing.contrib.apache.http.client.TracingClientExec.execute(TracingClientExec.java:82)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:107)

The stack trace shows what is happening. I'm not sure why the url from apache would be null in the case of a retry but I don't think the library should cause the retry to explode with an NPE?

**Comment by objectiser** [comment]
Version 0.6.0 of opentracing-api-extensions is now available in maven central.
